[package]
name = "makespan"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"
description = "Minimum makespan scheduler"
repository = "https://github.com/matyama/makespan"
license-file = "LICENSE"
keywords = ["scheduling", "makespan", "operations research"]
categories = ["algorithms", "science"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "makespan"
path = "src/lib.rs"

[dependencies]
num = "0.3"
ordered-float = "0.5"
