name: makespan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
# TODO: Setup [multiple builds](https://github.com/actions-rs/meta/blob/master/recipes/matrix.md)
#    strategy:
#      matrix:
#        rust:
#          - stable
#          - beta
#          - nightly
#          - 1.46.0  # MSRV TODO: Find actually minimal version

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

# TODO: Setup [cargo-deny](https://crates.io/crates/cargo-deny)
#    - name: Run dependency lint
#      run:
#        - cargo install cargo-deny
#        - cargo deny init
#        - cargo deny check

    - name: Run checks
      run: clippy --all-features -- -D warnings
      
    - name: Run tests
      run: cargo test --all-features --no-fail-fast
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests
        RUSTDOCFLAGS: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests
    
    # TODO: build docs

    - name: Generate coverage report
      id: coverage
      uses: actions-rs/grcov@v0.1

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ${{steps.coverage.outputs.report}}
        fail_ci_if_error: true
